### PR TITLE
KATI-31_Patient-Home-UI

### PR DESCRIPTION
**Pull request by vtnlinh95**

### CODE REVIEW

**Comment by vtnlinh95** [comment]
@hieumai fixed

**Comment by hieumai** [comment]
Looks OK to me. @huuduy216  and @toannguyen71195  please start verifying

**Comment by huuduy216** [comment]
@vtnlinh95 
-  Displaying multiple specialties problem.
- Vascular surgeon is selected by default, but does not available in the drop downlist

**Comment by vtnlinh95** [comment]
@huuduy216  @toannguyen71195  fixed

**Comment by huuduy216** [comment]
verified ok

**Comment by toannguyen71195** [comment]
@hieumai Verified

**Comment by hieumai** [comment]
OK. @vtnlinh95  please squash the commits so I can merge

**Pull request merged**
