### PR TITLE
KATI-37 Seed database and create APIs

### PR DESCRIPTION
**Pull request by toannguyen71195**

### CODE REVIEW

**Comment by hieumai** [comment]
Looks OK to me. @toannguyen71195 please squash commit to 1 commit. @huuduy216  and @vtnlinh95  please verify this pull request.

**Comment by huuduy216** [comment]
Tested, the API looks good

**Comment by vtnlinh95** [comment]
Verified OK

**Comment by hieumai** [comment]
@toannguyen71195  please deploy and tell me when you're finished

**Pull request merged**
